### ISSUE TITLE
`loc` instead `position` in node object?

### ISSUE THREAD

**Issue by tunnckoCore** [jonschlinkert/snapdragon#1]
to follow esprima/acorn format?

```json
{
  "loc": {
    "start": {
      "line": 82,
      "column": 0
    },
    "end": {
      "line": 87,
      "column": 3
    }
}
```

**Comment by jonschlinkert** [comment]
worth considering, but I'm not sure how important that is, or if esprima/acorn are the model to follow. I'll make it a feature request

**Comment by tunnckoCore** [comment]
I think with release of `0.5.0` we can close this, but only don't like that it is `lineno` not `line`., everything other is okey.

**Comment by jonschlinkert** [comment]
I might change it in 0.6.0 when the lexer is added

**Comment by jonschlinkert** [comment]
> we can close this

done, thanks

**Comment by tunnckoCore** [comment]
Okey, great. And one more note, why not `node.value` instead of `node.val`?

**Comment by jonschlinkert** [comment]
no real reason. the parser/renderer was originally based on one of TJ's libs CSS (mentioned on the readme) and it used `val`. 

Also, this might seem strange, but I tend to use short variable names specifically for variables that are repeated a bunch of times in a file - since in those cases the variable should be easily identifiable, and when a variable like that is long it makes it harder to scan for "[statistically improbable code](https://en.wikipedia.org/wiki/Statistically_improbable_phrase)". I like to be able to see what's important at a glance

**Comment by tunnckoCore** [comment]
Thought for that and I'm agree with you. Everyone will understand what `val` is, but I think it's better to be `value` because ASTs are more for humans. Worth nothing, don't know.
