### ISSUE TITLE
Dedupe dependencies.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [jonschlinkert/snapdragon#6]
Currently, there are multiple versions of several dependencies in the dependency tree.  This issue is meant to organize the deduplication of these.
- [x] `lazy-cache` (highest version in tree: `2.0.2`)
  - [x] `is-descriptor` requires `lazy-cache^1.0.3`.  PR: https://github.com/jonschlinkert/is-descriptor/pull/4.
  - [x] `class-utils` requires `lazy-cache^1.0.3`.  PR: https://github.com/jonschlinkert/class-utils/pull/2.
- [x] `to-object-path` (highest version in tree: `0.3.0`)
  - [x] The version of `set-value` required by `cache-base` requires `to-object-path^0.2.0`.  PR: https://github.com/jonschlinkert/cache-base/pull/7.
  - [x] The version of `set-value` required by `union-value` requires `to-object-path^0.2.0`.  PR: https://github.com/jonschlinkert/union-value/pull/2.
- [x] `isobject` (highest version in tree: `3.0.0`)
  - [x] `object-visit` requires `isobject^2.0.0`.  PR: https://github.com/jonschlinkert/object-visit/pull/1.
  - [x] `cache-base` requires `isobject^2.0.0`.  PR: https://github.com/jonschlinkert/cache-base/pull/7.
  - [x] `base` requires `isobject^2.0.0`.  PR: https://github.com/node-base/base/pull/26.
  - [x] `use` requires `isobject^2.0.0`.  PR: https://github.com/jonschlinkert/use/pull/9.
  - [x] `has-value` requires `isobject^2.0.0`.  PR: https://github.com/jonschlinkert/has-value/pull/2
  - [x] `unset-value` requires `isobject^2.0.0`.  PR: https://github.com/jonschlinkert/unset-value/pull/2.
  - [x] `class-utils` requires `isobject^2.0.0`.  PR: https://github.com/jonschlinkert/class-utils/pull/2
  - [x] The version of `set-value` required by `cache-base` requires `isobject^2.0.0`.  PR: https://github.com/jonschlinkert/cache-base/pull/7..
  - [x] The version of `set-value` required by `union-value` requires `isobject^2.0.0`.  PR: https://github.com/jonschlinkert/union-value/pull/2.
  - [x] `is-plain-object` requires `isobject^1.0.0`.  PR: https://github.com/jonschlinkert/is-plain-object/pull/8
- [x] `has-value` (highest version in tree: `0.3.1`)
  - [x] `unset-value` requires `has-value^0.2.0`.  PR: https://github.com/jonschlinkert/unset-value/pull/2.
- [x] `snapdragon-util` (highest version in tree: `2.1.1`)
  - [x] `snapdragon-node` requires `snapdragon-util^1.0.3`.  PR: https://github.com/jonschlinkert/snapdragon-node/pull/1.
- [ ] `kind-of` (highest version in tree: `5.0.2`)
  - [ ] `snapdragon-util` requires `kind-of@3.2.0`.

**Comment by jonschlinkert** [comment]
Per your comment on micromatch:

> If you've got a script that sorts that out over however many packages, that sounds pretty cool.

I have a library that updates all of the dependencies in a project to the latest version. I, and many other maintainers, typically close prs to upgrade deps for no reason. It's something that's done during routine updates when it makes sense. 

I find it odd that node.js developers have adopted a belief that deps should be updated axiomatically, every time a dependency changes versions.  If it's a serious bugfix, then it's taken care of already because it would be a patch. If it's more than a patch, there is a reason for it, and it also shouldn't be upgraded automatically.

**Comment by wtgtybhertgeghgtwtg** [comment]
It's not bumping dependencies for the sake of bumping dependencies, it's simplifying the tree.  There are scores of dependencies for the `micromatch` rewrite; if it can be helped, wouldn't it be better that it only uses a single version of `isobject`?  Isn't that the idea behind libraries like `isobject`, to have a single, standard implementation of a common function?

**Comment by jonschlinkert** [comment]
You're right, of course. I'm a big fan of optimization whenever possible, and I've made similar PRs myself, even recently. I'm just a little swamped atm and reacted a bit more harshly than I normally would. Apologies.  If you're willing to help me get them queued up, I'll try to merge them ASAP.

**Comment by wtgtybhertgeghgtwtg** [comment]
Thank you.  I will begin filing PR's as soon as possible.

**Comment by wtgtybhertgeghgtwtg** [comment]
Okay, I think that's all of them.

**Comment by wtgtybhertgeghgtwtg** [comment]
Right, so, `snapdragon` is almost entirely deduped.  Installing it now will only have `kind-of` and `snapdragon-util` duplicated.
The bad news is that this doesn't translate to deduplication for `nanomatch` (and therefore `micromatch`), partially because it still uses an old version of `snapdragon`.  Shall I make an issue there?

**Comment by jonschlinkert** [comment]
You can, but there is no advantage in upgrading snapdragon in the matching libs and it would require a lot of code changes to use the new snapdragon API. This seems like a good example of semver doing its job IMHO. I'd be happy to accept prs with all tests passing if you want to update the code too.

**Comment by wtgtybhertgeghgtwtg** [comment]
Actually, it looks like that won't be possible.  `micromatch` uses functionality that was removed in newer versions of `snapdragon` (index on `compiler.set`, `.prev`, et cetera).
I hope this doesn't come off wrong, but why did you change the API in a way that makes it incompatible with the most popular libraries that use `snapdragon`?  Won't that be a big problem if a security vulnerability is discovered?

**Comment by jonschlinkert** [comment]
What kind of security vulnerability? The entire point of the module system and semver is to have decoupled APIs.

**Comment by wtgtybhertgeghgtwtg** [comment]
> What kind of security vulnerability?

It's a hypothetical, I doubt there would be one.
But let's say somebody discovers a vulnerability in `snapdragon@0.8`, like there used to be in `minimatch`.  You can patch `snapdragon`, but `braces`, `expand-brackets`, `extglob`, `micromatch`, and `nanomatch` won't get that patch, since they're still using an old version of `snapdragon`.  And they can't use the new version because the API is incompatible.

> The entire point of the module system and semver is to have decoupled APIs.

That's true, but libraries exist for the sake of the programs that use them.  I am of the opinion that updates should be considerate of popular dependants.

**Comment by jonschlinkert** [comment]
Yes, that would be unlikely. But why wouldn't they get the patch? Also, all of the dependents are mine in this case, so I can easily control changes

**Comment by jonschlinkert** [comment]
I'm going to close this since it's not really a goal or "issue" of snapdragon's, this is more like your own todo list. But I'd be happy to take prs still.

**Comment by charlike** [comment]
This is one more case of why Semantic-Release + Renovate/GK combination would be good fit. You won't think. You may follow @tunnckoCore for a bit and see how i even don't know that they they are released, published and updated. And i don't care, there won't be a time that i will be out of date - never.

Yea, there is semver, and Renovate (specifically, because i'm kinda promoting it intentionally in the last weeks, because it _matters_, **really**) will respect it if you choose, but the automerge feature is just freaking awesome. For me it is one of the **main** selling points of Renovate, definitely.  You can configure it to respect and automerge only the minor versions (and only if tests pass, otherwise it will assign you, so you'll get notification), but not the major versions.

No matter of what your flow is, it is crazy configurable. Automation tools such as `semantic-release` is just bonus to this great deps keeper called RenovateApp.

Even if you (not exactly you) love semver and use the default's NPM behavior which is caret `^`, you still may benefit of that great auto-merge option of Renovate. Because some deps bump major without breaking change (like you bumped many of your packages in last months, because of the need [but not only] of the Gulp [team] to be major) . You bumped to v1 major of many of your packages, without any breaking changes and i still using them. So in such cases you may benefit of that automerge option.

But yea, probably in my flow the biggest thing is `semantic-release`. I didn't like it for months and used `standard-version` for that reason. But I didn't realized how great automation `semantic-release` gives you. Yea, it's awful by implementation and code behind, but fits well for the moment. I'm planning of releasing similar tool, too.
